### ISSUE TITLE
Altar presets

### ISSUE THREAD

**Issue by itsyourKitty** [raffel080108/AltarCrafting#1]
Hey! I don't know if i'm being stupid or not, but I'm reading the configs and I have no idea about the shape and placement of the blocks from the example altar and I don't know how to create one/how to set where the blocks need to be placed.

**Comment by raffel080108** [comment]
Oh yea, good point - I should've included some reference images maybe.
An example of a type 4 altar:
![image](https://user-images.githubusercontent.com/62069283/218540195-d475740e-bb8e-43ef-bdf2-1ef1a6c2ab4d.png)

An example of a type 8 altar:
![image](https://user-images.githubusercontent.com/62069283/218540249-7c1e8fb1-fea7-4bd0-bfb4-aed5e8a6a0b3.png)

The shape of the altar is always either of those 2. The only thing that changes is the material of the blocks.
I will add these reference images to the SpigotMC plugin page

**Comment by itsyourKitty** [comment]
Okay! Thank you!
