### ISSUE TITLE
Language file & Command output

### ISSUE THREAD

**Issue by itsyourKitty** [raffel080108/AltarCrafting#2]
A file for editing the messages would be pretty useful since some servers doesn't use english as main language!

And I don't know if it's possible or planned, but I would love to see a way to commands from console and/or from the player to be executed when the crafting is completed. Maybe a configuration where you can decide if you want the output to be the item, the command or both. Amazing plugin!

**Comment by raffel080108** [comment]
Good idea, actually - I will implement a messages.yml file that includes some modifiable messages
It should be easy enough to implement your second suggestion aswell. I will add an option in the configuration to dispatch a command upon recipe completion (optionally replacing the resulting item output)

**Comment by raffel080108** [comment]
Both requests implemented in version 1.3
