### ISSUE TITLE
Custom model data and NBT data for recipes

### ISSUE THREAD

**Issue by omgitsKit** [raffel080108/AltarCrafting#3]
Hello!

I would love to be able to have custom items (from itemsadder, for example) in recipes as ingredients and as results. This could be achieved using custom model data from items, like placing "iron_nugget{1001}" in the recipes file or by adding items to the recipe in game through a command, like "/ingredient add (recipe name)" and it would add the item in the hand to the recipe.

**Comment by raffel080108** [comment]
Hi, sorry, I apparently didn't receive a notification from this issue or I just didn't see it...

What you mean is an option to provide a required custom model-data for input or a custom model-data to apply for output items, correct? 

As to your second suggestion (I'm interpreting it as that), it would require a lot of manual implementation to make a command like that work. I would basically need to make a whole system to reverse the configuration reading process. I think using the configuration is good enough

**Comment by raffel080108** [comment]
The option to provide custom model-data for an item has been implemented in version **1.3.4**

If your feature request was intended differently, please re-open this issue with a comment or open a new issue regarding it

**Comment by omgitsKit** [comment]
Hello! Just wanted to thank you for the implementation and I wanted to clarify something too: Theres some issue while trying to add the custom-model-data nbt parameter to ingredientes, but it seems to work flawlessly with the result item. Not sure if i'm doing something wrong, tho. Take a look! 
![image](https://github.com/raffel080108/AltarCrafting/assets/116936416/47abb5e4-4bd8-4b50-8b03-0afc5bc236df)

**Comment by raffel080108** [comment]
Could you please describe what exactly the issue is, I cannot see an issue on this screenshot
